import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  outputFileTracingExcludes: {
    "/*": [
      "./node_modules/@next/swc-*/**/*",
      "./node_modules/prisma/**/*",
      "./node_modules/@prisma/engines/**/*",
      "./node_modules/typescript/**/*",
      "./node_modules/playwright/**/*",
      "./node_modules/playwright-core/**/*",
      "./node_modules/@playwright/**/*",
      "./node_modules/vitest/**/*",
      "./node_modules/@vitest/**/*",
      "./node_modules/jsdom/**/*",
      "./node_modules/eslint/**/*",
      "./node_modules/eslint-*/**/*",
      "./node_modules/@eslint/**/*",
      "./node_modules/tsx/**/*",
      "./node_modules/@testing-library/**/*",
      "./node_modules/@esbuild/**/*",
      "./node_modules/esbuild/**/*",
      "./node_modules/@rolldown/**/*",
      "./node_modules/rolldown/**/*",
      "./node_modules/lightningcss*/**/*",
      "./node_modules/@tailwindcss/**/*",
      "./node_modules/tailwindcss/**/*",
      "./node_modules/jiti/**/*",
      "./node_modules/dotenv/**/*",
      "./node_modules/effect/**/*",
      "./node_modules/@typescript-eslint/**/*",
      "./node_modules/vite/**/*",
      "./node_modules/@vitejs/**/*",
      "./node_modules/axe-core/**/*",
      "./node_modules/es-abstract/**/*",
      "./node_modules/fast-check/**/*",
      "./node_modules/@unrs/resolver-binding-*/**/*",
      "./node_modules/hermes-parser/**/*",
      "./node_modules/css-tree/**/*",
      "./node_modules/tldts/**/*",
      "./node_modules/mdn-data/**/*",
      "./node_modules/language-subtag-registry/**/*",
      "./node_modules/@prisma/get-platform/**/*",
      "./node_modules/@prisma/fetch-engine/**/*",
      "./node_modules/@prisma/client/runtime/query_engine_bg.cockroachdb.*",
      "./node_modules/@prisma/client/runtime/query_engine_bg.mysql.*",
      "./node_modules/@prisma/client/runtime/query_engine_bg.sqlite.*",
      "./node_modules/@prisma/client/runtime/query_engine_bg.sqlserver.*",
      "./node_modules/@prisma/client/runtime/query_compiler_bg.cockroachdb.*",
      "./node_modules/@prisma/client/runtime/query_compiler_bg.mysql.*",
      "./node_modules/@prisma/client/runtime/query_compiler_bg.sqlite.*",
      "./node_modules/@prisma/client/runtime/query_compiler_bg.sqlserver.*",
    ],
  },
};

export default nextConfig;
